export const ROUTES = {
  home: "/",
  products: "/products",
  productDetail: "/products/:productId",
  subscription: "/subscription",
  reservation: "/reservation",
  reservationClass: "/reservation/class",
  tasteTest: "/taste-test",
  myPage: "/mypage",
  myPageManage: "/mypage/manage/:sectionId",
  myBlend: "/my-blend",
  cart: "/cart",
  purchase: "/purchase",
  login: "/login",
  signup: "/signup",
  search: "/search",
  orders: "/orders",
  qr: "/qr",
  offline: "/offline",
} as const;
