export const ROUTES = {
  home: "/",
  products: "/products",
  productDetail: "/products/:productId",
  brewingStory: "/brewing-story",
  tasteTest: "/taste-test",
  myPage: "/mypage",
  cart: "/cart",
  purchase: "/purchase",
  addressBook: "/addresses",
  guestOrders: "/guest-orders",
  login: "/login",
  signup: "/signup",
  search: "/search",
  orders: "/orders",
  offline: "/offline",
} as const;
